# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.FileField(upload_to='')),
                ('no', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.Image')),
            ],
            options={
                'ordering': ('no',),
            },
        ),
    ]
