# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_auto_20170705_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='verify',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
