# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import exp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_image_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='xml',
            field=models.FileField(upload_to='', validators=[exp.validators.validate_file_extension]),
        ),
    ]
